In [1]:
import pandas as pd
import numpy as np

In [2]:
file = "/Users/miguelparedes/Desktop/gitrepos/ncov-king-county/data/sequenced_kingco_3.22.22.csv"

In [3]:
df = pd.read_csv(file)

In [4]:
df[df.GISAID_ID == 'USA/WA-S101/2020']

      Unnamed: 0  ID         GISAID_ID POSTAL_CODE AGE_DECADE COUNTY
7638        7639   5  USA/WA-S101/2020       98028    Age 90+   King

In [5]:
df['ID'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
33707    False
33708    False
33709    False
33710    False
33711    False
Name: ID, Length: 33712, dtype: bool

In [6]:
u_df =df[df['ID'].duplicated() == False]

In [10]:
u_df[u_df['POSTAL_CODE'] == 'USA'] = np.nan
u_df[u_df['POSTAL_CODE'] == 'undef-ined'] = np.nan
u_df[u_df['POSTAL_CODE'] == 'UNDEF'] = np.nan
u_df = u_df.dropna(subset=['POSTAL_CODE'])

In [11]:
for index, row in u_df.iterrows():
    u_df.loc[index, 'POSTAL_CODE'] = row['POSTAL_CODE'].split('-')[0]

In [12]:
u_df['PUMA'] = np.nan
u_df['POSTAL_CODE'] = u_df['POSTAL_CODE'].astype('int')

ValueError: invalid literal for int() with base 10: ','

In [ ]:
for index, rows in u_df.iterrows():
    if rows.POSTAL_CODE in (98103, 98107, 98117):
        u_df.loc[index, 'PUMA'] = "11601" 
    elif rows.POSTAL_CODE in (98105, 98115, 98125, 98195):
        u_df.loc[index, 'PUMA'] = "11602" 
    elif rows.POSTAL_CODE in (98101, 98102, 98104, 98109, 98119, 98121, 98154, 98164, 98199):
        u_df.loc[index, 'PUMA'] = "11603" 
    elif rows.POSTAL_CODE in (98112, 98118, 98122, 98144):
        u_df.loc[index, 'PUMA'] = "11604" 
    elif rows.POSTAL_CODE in (98106, 98108, 98116, 98126, 98134, 98136):
        u_df.loc[index, 'PUMA'] = "11605" 
    elif rows.POSTAL_CODE in (98133, 98155, 98177, 98011, 98028):
        u_df.loc[index, 'PUMA'] = "11606" 
    elif rows.POSTAL_CODE in (98033, 98034, 98052):
        u_df.loc[index, 'PUMA'] = "11607" 
    elif rows.POSTAL_CODE in (98004, 98005, 98006, 98007, 98008, 98039):
        u_df.loc[index, 'PUMA'] = "11608" 
    elif rows.POSTAL_CODE in (98040, 98029, 98074, 98075):
        u_df.loc[index, 'PUMA'] = "11609" 
    elif rows.POSTAL_CODE in (98055, 98057, 98056, 98178):
        u_df.loc[index, 'PUMA'] = "11610" 
    elif rows.POSTAL_CODE in (98146, 98148, 98166, 98168, 98188):
        u_df.loc[index, 'PUMA'] = "11611" 
    elif rows.POSTAL_CODE in (98003, 98023, 98198, 98070):
        u_df.loc[index, 'PUMA'] = "11612" 
    elif rows.POSTAL_CODE in (98030, 98031, 98032, 98092):
        u_df.loc[index, 'PUMA'] = "11613" 
    elif rows.POSTAL_CODE in (98001, 98002, 98047):
        u_df.loc[index, 'PUMA'] = "11614" 
    elif rows.POSTAL_CODE in (98010, 98022, 98038, 98051, 98027, 98042, 98059, 98058):
        u_df.loc[index, 'PUMA'] = "11615" 
    elif rows.POSTAL_CODE in (98045, 98065, 98014, 98077, 98053, 98024, 98072, 98019):
        u_df.loc[index, 'PUMA'] = "11616"

In [30]:
snippet = ['CA', 'CT', 'ID', 'UN', 'KY']
for index, row in u_df.iterrows():
    for item in snippet: 
        if item in row.GISAID_ID:
            print('pass')
            u_df.loc[index, 'GISAID_ID'] = np.nan

pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass

In [31]:
u_df = u_df.dropna(subset = ['GISAID_ID'])

In [32]:
u_df = u_df.rename(columns={'GISAID_ID': 'strain'})

u_df = u_df.rename(columns={'PUMA': 'Puma'})

In [33]:
u_df[u_df.strain == 'USA/WA-S101/2020']

Empty DataFrame
Columns: [ID, strain, POSTAL_CODE, AGE_DECADE, COUNTY, Puma]
Index: []

In [34]:
final_df = u_df[['strain', 'Puma', 'COUNTY']].copy()

In [35]:
final_df

                                           strain   Puma COUNTY
0                   USA/WA-CDC-UW21092587253/2021  11616   King
1                   USA/WA-CDC-UW21092537491/2021  11613   King
2                   USA/WA-CDC-UW21100155619/2021  11603   King
3                      USA/WA-UW-21041369684/2021  11601   King
4                      USA/WA-UW-21041217371/2021  11601   King
...                                           ...    ...    ...
21256                   USA/WA-CDC-LC0044856/2021  11612   King
21257                  USA/WA-UW-21051106844/2021  11614   King
21258                  USA/WA-UW-21042204444/2021  11607   King
21259  USA/WA-Altius-ALTCOV-SXY7JSOF73BGEVTC/2021  11611   King
21260               USA/WA-CDC-UW21070891696/2021  11615   King

[20152 rows x 3 columns]

In [36]:
final_df.to_csv('fullkc_puma.tsv', sep = "\t")