In [1]:
import pandas as pd
import numpy as np

In [2]:
file = "data/sequenced_kingco_8.12.22"

In [3]:
df = pd.read_csv(file)

FileNotFoundError: [Errno 2] No such file or directory: 'data/sequenced_kingco_8.12.22'

In [38]:
df[df.GISAID_ID == 'USA/WA-S101/2020']

      Unnamed: 0  ID         GISAID_ID POSTAL_CODE AGE_DECADE COUNTY
7638        7639   5  USA/WA-S101/2020       98028    Age 90+   King

In [39]:
df['ID'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
33707    False
33708    False
33709    False
33710    False
33711    False
Name: ID, Length: 33712, dtype: bool

In [40]:
u_df =df[df['ID'].duplicated() == False]

In [41]:
u_df[u_df['POSTAL_CODE'] == 'USA'] = np.nan
u_df[u_df['POSTAL_CODE'] == 'undef-ined'] = np.nan
u_df[u_df['POSTAL_CODE'] == 'UNDEF'] = np.nan
u_df[u_df['POSTAL_CODE'] == ','] = np.nan
u_df = u_df.dropna(subset=['POSTAL_CODE'])

/Users/miguelparedes/anaconda3/envs/nextstrain/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/miguelparedes/anaconda3/envs/nextstrain/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/miguelparedes/anaconda3/envs/nextstrain/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/miguelparedes/anaconda3/envs/nextstrain/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/miguelparedes/anaconda3/envs/nextstrain/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [42]:
for index, row in u_df.iterrows():
    u_df.loc[index, 'POSTAL_CODE'] = row['POSTAL_CODE'].split('-')[0]

In [43]:
u_df['PUMA'] = np.nan
u_df['POSTAL_CODE'] = u_df['POSTAL_CODE'].astype('int')

In [44]:
u_df

,Unnamed: 0,ID,GISAID_ID,POSTAL_CODE,AGE_DECADE,COUNTY,PUMA
0,1.0,13891.0,USA/WA-Altius-ALTCOV-PAINETRD6YCX72UC/2021,98023,Age 0-9,King,NaN
1,2.0,13814.0,USA/WA-S10305/2021,98059,Age 30-39,King,NaN
2,3.0,4251.0,USA/WA-UW-64698/2021,98198,Age 20-29,King,NaN
3,4.0,3051.0,USA/WA-S4077/2021,98042,Age 0-9,King,NaN
4,5.0,4145.0,USA/WA-UW-62350/2021,98115,Age 20-29,King,NaN
...,...,...,...,...,...,...,...
33707,33708.0,23154.0,USA/WA-CDC-UW21120137629/2021,98116,Age 30-39,King,NaN
33708,33709.0,20235.0,USA/WA-UW-21100629440/2021,98103,Age 40-49,King,NaN
33709,33710.0,21348.0,USA/WA-PHL-005644/2021,98059,Age 50-59,King,NaN
33710,33711.0,22418.0,USA/WA-UW-21111550085/2021,98028,Age 20-29,King,NaN
33711,33712.0,31692.0,USA/WA-CDC-UW22022101668/2022,98103,Age 30-39,King,NaN

In [45]:
for index, rows in u_df.iterrows():
    if rows.POSTAL_CODE in (98103, 98107, 98117):
        u_df.loc[index, 'PUMA'] = "11601" 
    elif rows.POSTAL_CODE in (98105, 98115, 98125, 98195):
        u_df.loc[index, 'PUMA'] = "11602" 
    elif rows.POSTAL_CODE in (98101, 98102, 98104, 98109, 98119, 98121, 98154, 98164, 98199):
        u_df.loc[index, 'PUMA'] = "11603" 
    elif rows.POSTAL_CODE in (98112, 98118, 98122, 98144):
        u_df.loc[index, 'PUMA'] = "11604" 
    elif rows.POSTAL_CODE in (98106, 98108, 98116, 98126, 98134, 98136):
        u_df.loc[index, 'PUMA'] = "11605" 
    elif rows.POSTAL_CODE in (98133, 98155, 98177, 98011, 98028):
        u_df.loc[index, 'PUMA'] = "11606" 
    elif rows.POSTAL_CODE in (98033, 98034, 98052):
        u_df.loc[index, 'PUMA'] = "11607" 
    elif rows.POSTAL_CODE in (98004, 98005, 98006, 98007, 98008, 98039):
        u_df.loc[index, 'PUMA'] = "11608" 
    elif rows.POSTAL_CODE in (98040, 98029, 98074, 98075):
        u_df.loc[index, 'PUMA'] = "11609" 
    elif rows.POSTAL_CODE in (98055, 98057, 98056, 98178):
        u_df.loc[index, 'PUMA'] = "11610" 
    elif rows.POSTAL_CODE in (98146, 98148, 98166, 98168, 98188):
        u_df.loc[index, 'PUMA'] = "11611" 
    elif rows.POSTAL_CODE in (98003, 98023, 98198, 98070):
        u_df.loc[index, 'PUMA'] = "11612" 
    elif rows.POSTAL_CODE in (98030, 98031, 98032, 98092):
        u_df.loc[index, 'PUMA'] = "11613" 
    elif rows.POSTAL_CODE in (98001, 98002, 98047):
        u_df.loc[index, 'PUMA'] = "11614" 
    elif rows.POSTAL_CODE in (98010, 98022, 98038, 98051, 98027, 98042, 98059, 98058):
        u_df.loc[index, 'PUMA'] = "11615" 
    elif rows.POSTAL_CODE in (98045, 98065, 98014, 98077, 98053, 98024, 98072, 98019):
        u_df.loc[index, 'PUMA'] = "11616"

In [46]:
snippet = ['CA', 'CT', 'ID', 'UN', 'KY']
for index, row in u_df.iterrows():
    for item in snippet: 
        if item in row.GISAID_ID:
            #print('pass')
            u_df.loc[index, 'GISAID_ID'] = np.nan

In [47]:
u_df

,Unnamed: 0,ID,GISAID_ID,POSTAL_CODE,AGE_DECADE,COUNTY,PUMA
0,1.0,13891.0,USA/WA-Altius-ALTCOV-PAINETRD6YCX72UC/2021,98023,Age 0-9,King,11612
1,2.0,13814.0,USA/WA-S10305/2021,98059,Age 30-39,King,11615
2,3.0,4251.0,USA/WA-UW-64698/2021,98198,Age 20-29,King,11612
3,4.0,3051.0,USA/WA-S4077/2021,98042,Age 0-9,King,11615
4,5.0,4145.0,USA/WA-UW-62350/2021,98115,Age 20-29,King,11602
...,...,...,...,...,...,...,...
33707,33708.0,23154.0,USA/WA-CDC-UW21120137629/2021,98116,Age 30-39,King,11605
33708,33709.0,20235.0,USA/WA-UW-21100629440/2021,98103,Age 40-49,King,11601
33709,33710.0,21348.0,USA/WA-PHL-005644/2021,98059,Age 50-59,King,11615
33710,33711.0,22418.0,USA/WA-UW-21111550085/2021,98028,Age 20-29,King,11606
33711,33712.0,31692.0,USA/WA-CDC-UW22022101668/2022,98103,Age 30-39,King,11601

In [48]:
u_df = u_df.dropna(subset = ['GISAID_ID'])

In [49]:
u_df = u_df.rename(columns={'GISAID_ID': 'strain'})

u_df = u_df.rename(columns={'PUMA': 'Puma'})

In [50]:
u_df[u_df.strain == 'USA/WA-S101/2020']

Empty DataFrame
Columns: [Unnamed: 0, ID, strain, POSTAL_CODE, AGE_DECADE, COUNTY, Puma]
Index: []

In [51]:
final_df = u_df[['strain', 'Puma', 'COUNTY']].copy()

In [52]:
final_df

                                           strain   Puma COUNTY
0      USA/WA-Altius-ALTCOV-PAINETRD6YCX72UC/2021  11612   King
1                              USA/WA-S10305/2021  11615   King
2                            USA/WA-UW-64698/2021  11612   King
3                               USA/WA-S4077/2021  11615   King
4                            USA/WA-UW-62350/2021  11602   King
...                                           ...    ...    ...
33707               USA/WA-CDC-UW21120137629/2021  11605   King
33708                  USA/WA-UW-21100629440/2021  11601   King
33709                      USA/WA-PHL-005644/2021  11615   King
33710                  USA/WA-UW-21111550085/2021  11606   King
33711               USA/WA-CDC-UW22022101668/2022  11601   King

[32124 rows x 3 columns]

In [53]:
final_df.to_csv('/Users/miguelparedes/Desktop/gitrepos/kc_puma_build/data/fullkc_puma.tsv', sep = "\t")